[package]
name = "risp"
version = "0.1.0"
authors = ["Nikita Pekin <nikita@frecency.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
rustyline = "6.3.0"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"
